"""Compile approved Korean DMAP artwork and overlay the current integrated ISO.

Artwork is generated by the built-in image tool; this script only resamples to
the game's native resolution, encodes the original indexed format, and packs it.
"""
import argparse
import json
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'build/python_psd'))
import numpy as np
from PIL import Image, ImageDraw
from localization_pipeline import sha, file_hash, hed_tree, write_json
from iso_archive_stage import iso_inventory, exact, overlay
from ui_texture_codec import parse, serialize, unpack_indices, preview_rgba, uad_rectangles
from build_battle_conditions_psd import compile_texture
import build_user_translation_import as verifier

OUT = ROOT / 'outputs/dmap_map_ko_v1'
BUILD = ROOT / 'build/dmap_map_ko_v1'
BASE = ROOT / 'build/user_ui_test_v6/Poison Pink (Japan) - Korean user UI test v6.iso'
BASE_SHA = '3086890c313ffcbf1303671e3e0f11a1dded4194c0ad742cb54a59e61b5b3771'
ISO = BUILD / 'Poison Pink (Japan) - Korean DMAP maps v1.iso'
RAW = ROOT / 'extracted/original/raw'


def manifest():
    rows = json.loads((OUT / 'manifest.json').read_text())
    extra = OUT / 'extra_manifest.json'
    if extra.exists():
        rows.extend(json.loads(extra.read_text()))
    return rows


def compile_assets():
    assets = []
    missing = []
    cache_file = BUILD / 'assets.json'
    cache = {r['member']: r for r in json.loads(cache_file.read_text())['pending_assets']} if cache_file.exists() else {}
    for row in manifest():
        src = OUT / 'generations' / (row['id'] + '.png')
        if not src.exists():
            missing.append(row['id'])
            continue
        for source in [row['source']] + row['duplicates']:
            rel = source.split('extracted/original/images/', 1)[1][:-4]
            raw = (RAW / rel).read_bytes()
            cached = cache.get(rel.split('/', 1)[1])
            if cached and cached['generation_sha256'] == file_hash(src):
                dest = ROOT / cached['replacement']
                if dest.exists() and file_hash(dest) == cached['sha256']:
                    assert sha(raw) == cached['expected_original_sha256']
                    assets.append(cached)
                    continue
            model = parse(raw)
            native = Image.open(src).convert('RGBA').resize(
                (model['width'], model['height']), Image.Resampling.LANCZOS)
            if row['id'].startswith('name'):
                # These labels are sampled from a bounded area of their atlas.
                # Fit the generated alpha bounds to the original ink rectangle.
                art = Image.open(src).convert('RGBA')
                bounds = art.getchannel('A').point(lambda x: 255 if x > 20 else 0).getbbox()
                original = Image.frombytes('RGBA', native.size, preview_rgba(model))
                box = original.getchannel('A').point(lambda x: 255 if x > 20 else 0).getbbox()
                native = Image.new('RGBA', native.size)
                native.paste(art.crop(bounds).resize((box[2]-box[0], box[3]-box[1]),
                    Image.Resampling.LANCZOS), box[:2])
            data, checks = compile_texture(raw, native)
            encoded = parse(data)
            old = np.frombuffer(unpack_indices(model), np.uint8).reshape(model['height'], model['width'])
            new = np.frombuffer(unpack_indices(encoded), np.uint8).reshape(old.shape).copy()
            uad = (RAW / rel).with_suffix('.uad')
            if row['id'].startswith('vd'):
                assert (model['width'], model['height'], model['bpp']) == (512, 512, 8)
                assert uad_rectangles(uad.read_bytes(), 512, 512)['rectangles'][0]['rect'] == [0, 0, 512, 448]
                new[448:] = old[448:]
                assert np.array_equal(new[448:], old[448:])
            encoded['indices'] = new.tobytes() if model['bpp'] == 8 else bytes(
                int(a) | int(b) << 4 for a, b in zip(new.ravel()[::2], new.ravel()[1::2]))
            data = serialize(encoded)
            assert encoded['header'] == model['header'] and encoded['palette'] == model['palette']
            assert len(data) == len(raw) and serialize(parse(data)) == data
            dest = BUILD / 'textures' / rel
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_bytes(data)
            preview = Image.frombytes('RGBA', native.size, preview_rgba(parse(data)))
            png = OUT / 'native' / (rel + '.png')
            png.parent.mkdir(parents=True, exist_ok=True)
            preview.save(png)
            assets.append(dict(archive='DMAP', member=rel.split('/', 1)[1],
                replacement=str(dest.relative_to(ROOT)), sha256=sha(data),
                expected_original_sha256=sha(raw), generation_sha256=file_hash(src),
                original_png=source, preview=str(png.relative_to(ROOT)),
                uad_sha256=file_hash(uad) if uad.exists() else None,
                checks=checks, roundtrip_verified=True))
    report = dict(status='prepared_not_applied_to_iso', missing=missing,
        prepared_count=len(assets), expected_vd_count=73, pending_assets=assets,
        image_generation_mode='built-in image_gen', runtime_verified=False)
    write_json(BUILD / 'assets.json', report)
    print(json.dumps(dict(prepared=len(assets), missing=len(missing)), ensure_ascii=False), flush=True)
    return report


def build():
    report = json.loads((BUILD / 'assets.json').read_text())
    assert not report['missing'], report['missing']
    assert len(report['pending_assets']) == 75, 'Expected 73 prebattle images and two special labels'
    review = json.loads((OUT / 'visual_review.json').read_text())
    assert review['native_preview_review_complete']
    assert review['approved_ids'] == sorted(r['id'] for r in manifest())
    for row in manifest():
        assert review['sha256'][row['id']] == file_hash(OUT / 'generations' / (row['id'] + '.png'))
    inv = iso_inventory(BASE)
    files = {e['path']: e for e in inv['files']}
    patches = []
    records = []
    with BASE.open('rb') as f:
        he, de = files['DATA/DMAP.HED'], files['DATA/DMAP.DAT']
        f.seek(he['lba'] * 2048)
        members = {e['path']: e for e in hed_tree(exact(f, he['size']))[0]}
        for asset in report['pending_assets']:
            e = members[asset['member']]
            pos = de['lba'] * 2048 + e['offset']
            f.seek(pos)
            old = exact(f, e['size'])
            assert sha(old) == asset['expected_original_sha256'], asset['member']
            data = (ROOT / asset['replacement']).read_bytes()
            assert sha(data) == asset['sha256'] and len(data) == len(old)
            patches.append(dict(offset=pos, data=data, expected_sha256=sha(old)))
            records.append(dict(member=asset['member'], offset=pos, size=len(data), sha256=sha(data)))
        # The handover requests these already prepared changes in the next ISO.
        pending = json.loads((ROOT / 'reports/class_change_review_v1.json').read_text())
        assert pending['base_iso_sha256'] == BASE_SHA
        for asset in pending['pending_files']:
            e = files[asset['path']]
            pos = e['lba'] * 2048
            f.seek(pos)
            old = exact(f, e['size'])
            assert sha(old) == asset['expected_sha256']
            data = (ROOT / asset['replacement']).read_bytes()
            assert sha(data) == asset['sha256'] and len(data) == len(old)
            patches.append(dict(offset=pos, data=data, expected_sha256=sha(old)))
            records.append(dict(file=asset['path'], offset=pos, size=len(data), sha256=sha(data)))
    print('Building and verifying complete ISO', flush=True)
    result = overlay(BASE, ISO, patches, BASE_SHA)
    assert iso_inventory(ISO) == inv
    verifier.BASE_HASH = BASE_SHA
    verified = verifier.verify_stream(BASE, ISO, patches, result['output_sha256'])
    assert verified['passed']
    with ISO.open('rb') as f:
        for r in records:
            f.seek(r['offset'])
            assert sha(exact(f, r['size'])) == r['sha256']
    report.update(status='applied_to_iso', iso_path=str(ISO.relative_to(ROOT)),
        base_iso=str(BASE.relative_to(ROOT)), iso=result, replacements=records,
        whole_iso_verification=verified, runtime_verified=False,
        date='2026-10-01', scope_images=1353, newly_localized_images=75,
        existing_korean_bstart_images_preserved=137,
        includes_pending_class_shop_controller_messages=True)
    report['applied_assets'] = report.pop('pending_assets')
    write_json(BUILD / 'report.json', report)
    write_json(ROOT / 'reports/dmap_map_ko_v1.json', report)
    (BUILD / 'SHA256SUMS.txt').write_text(result['output_sha256'] + '  ' + ISO.name + '\n')
    side = Path(str(ISO) + '.pcsx2')
    assert json.loads((side / 'manifest.json').read_text())['iso_sha256'] == result['output_sha256']
    with zipfile.ZipFile(BUILD / 'PCSX2_대화표시_호환패키지.zip', 'w', zipfile.ZIP_DEFLATED) as z:
        for p in sorted(side.rglob('*')):
            if p.is_file():
                z.write(p, p.relative_to(side))
    with zipfile.ZipFile(BUILD / 'PCSX2_대화표시_호환패키지.zip') as z:
        assert z.testzip() is None
    (BUILD / '먼저읽기.txt').write_text('DMAP 지도 이미지 한글화 v1\n전투 시작 화면 73장과 마신 파쇄기·카멜리아 2장 적용. 기존 한글화와 적용 대기 클래스·상점·컨트롤러 문구 포함.\n원본 TIM2 크기·헤더·팔레트, UAD와 아카이브 위치 유지. 전체 ISO 계획 밖 바이트 일치 확인.\n생성형 이미지 편집으로 배경의 세부 표현에 차이가 있을 수 있습니다. 실제 게임 실행 미검증.\n새 ISO로 부팅하고 함께 제공된 PCSX2 대화 표시 호환 패치를 사용하세요.\n')
    with (BUILD / '먼저읽기.txt').open('a') as f:
        f.write('이 ISO의 ELF CRC: '+result['runtime_compatibility']['elf_crc']+'\n이전 CRC용 패치만으로는 새 ISO에 적용되지 않습니다. 새 패치를 사용하고 게임 내 저장을 불러오세요.\n')
    cfg_path = ROOT / 'localization/pipeline.json'
    cfg = json.loads(cfg_path.read_text())
    cfg['latest_experimental_build'] = dict(path=report['iso_path'],
        sha256=result['output_sha256'], pcsx2_sidecar=report['iso_path']+'.pcsx2',
        report='reports/dmap_map_ko_v1.json', runtime_verified=False)
    cfg['static_checks']['dmap_map_ko_v1_entire_iso_verified'] = True
    write_json(cfg_path, cfg)
    for name in ['class_change_review_v1', 'remaining_messages_v1', 'shop_messages_v1']:
        rp = ROOT / 'reports' / (name + '.json')
        previous = json.loads(rp.read_text())
        previous.update(status='applied_to_iso', iso_built=True,
            iso_path=report['iso_path'], integration_report='reports/dmap_map_ko_v1.json',
            applied_via='class_change_review_v1', runtime_verified=False)
        write_json(rp, previous)
    handover = ROOT / 'HANDOVER.md'
    text = handover.read_text()
    text = text.replace('## 최신 실행 ISO: 사용자 UI 중간 테스트 v6', '## 이전 기반 ISO: 사용자 UI 중간 테스트 v6', 1)
    for heading in ['클래스 체인지 전체 문구 검수', '추가 안내문 통합', '상점 수량·확인 대사']:
        text = text.replace('## 적용 대기: '+heading, '## 준비 당시 기록 (DMAP v1 반영 완료): '+heading, 1)
    section = ('## 최신 실행 ISO: DMAP 지도 이미지 한글화 v1 (2026-10-01)\n\n'
        + '`'+report['iso_path']+'`\nSHA-256: `'+result['output_sha256']+'`.\n\n'
        + 'UI test v6 기반. DMAP/dmap/map 전체 1,353장 검토; 전투 시작 화면 73장과 특수 명칭 2장 추가, 기존 bstart 한글 이미지 137장 유지. '
        + '이전에 준비된 클래스·상점·컨트롤러 문구도 class_change_review_v1의 3개 파일로 통합.\n\n'
        + '내장 이미지 생성 도구 사용. 원본 TM2 크기·헤더·팔레트·파일 길이 보존, UAD 및 ISO 계획 범위 밖 전체 바이트 동일 확인. '
        + '생성형 편집으로 배경 세부 표현 차이가 있음. 실제 게임 실행은 미검증. PCSX2 CRC '+result['runtime_compatibility']['elf_crc']+'용 호환 sidecar/ZIP 동봉. '
        + '보고서 reports/dmap_map_ko_v1.json; 이미지·프롬프트·검수 자료 outputs/dmap_map_ko_v1; 빌더 tools/build_dmap_map_ko_v1.py.\n\n')
    handover.write_text(text.replace('\n\n', '\n\n'+section, 1))
    print(json.dumps(dict(iso=str(ISO), sha256=result['output_sha256'], verified=verified), ensure_ascii=False), flush=True)


if __name__ == '__main__':
    ap = argparse.ArgumentParser()
    ap.add_argument('--build', action='store_true')
    args = ap.parse_args()
    BUILD.mkdir(parents=True, exist_ok=True)
    if args.build:
        build()
    else:
        compile_assets()
